# Generated by Django 5.1.7 on 2025-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amazon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amazon_reviews', models.TextField()),
                ('amazon_image', models.ImageField(upload_to='amazon_images/')),
                ('amazon_url', models.URLField()),
                ('flipkart_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flipkart_reviews', models.TextField()),
                ('flipkart_image', models.ImageField(upload_to='flipkart_images/')),
                ('flipkart_url', models.URLField()),
            ],
        ),
    ]
